---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-operator.fullname" . }}
  labels:
    {{- include "project-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "project-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "project-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
      - {{ toYaml . | trim | nindent 8 }}
        {{- if not .labelSelector }}
        labelSelector:
          matchLabels:
            {{- include "project-operator.selectorLabels" $ | nindent 12 }}
        {{- end }}
      {{- end }}
      {{- else }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        nodeTaintsPolicy: Honor
        whenUnsatisfiable: {{ .Values.defaultHostNameSpreadPolicy  }}
        labelSelector:
          matchLabels:
            {{- include "project-operator.selectorLabels" . | nindent 12 }}
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        nodeTaintsPolicy: Honor
        whenUnsatisfiable: {{ .Values.defaultZoneSpreadPolicy  }}
        labelSelector:
          matchLabels:
            {{- include "project-operator.selectorLabels" . | nindent 12 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "project-operator.fullname" . }}
      automountServiceAccountToken: true
      containers:
      - name: controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: webhooks
          containerPort: 9443
          protocol: TCP
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: probes
          containerPort: 8081
          protocol: TCP
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            port: probes
            scheme: HTTP
            path: /healthz
        readinessProbe:
          httpGet:
            port: probes
            scheme: HTTP
            path: /readyz
        args:
        - "--leader-elect=true"
        {{- with .Values.namespacePrefix }}
        - "--namespace-prefix={{ . }}"
        {{- end }}
        {{- with .Values.adminClusterRole }}
        - "--admin-cluster-role={{ . }}"
        {{- end }}
        {{- with .Values.viewerClusterRole }}
        - "--viewer-cluster-role={{ . }}"
        {{- end }}
        {{- with .Values.enableClusterView }}
        - "--enable-cluster-view"
        {{- end }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: {{ include "project-operator.fullname" . }}-{{ ternary "tls-managed" "tls" .Values.webhook.certManager.enabled }}
