{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "project-operator.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "project-operator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- if .Values.monitoring.rules }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "project-operator.fullname" . }}
spec:
  groups:
  - name: project-operator-alerts
    rules:
    {{- toYaml .Values.monitoring.rules | nindent 4 }}
{{- end }}
{{- end }}
