{{- $caCert := "" }}
{{- if .Values.webhook.certManager.enabled }}
{{- if not .Values.webhook.certManager.issuerName }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "project-operator.fullname" . }}
  labels:
    {{- include "project-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "project-operator.fullname" . }}
  labels:
    {{- include "project-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "project-operator.fullname" . }}
  - {{ include "project-operator.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "project-operator.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "project-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.webhook.certManager.issuerName }}
    {{- with .Values.webhook.certManager.issuerGroup }}
    group: {{ . }}
    {{- end }}
    {{- with .Values.webhook.certManager.issuerKind }}
    kind: {{ . }}
    {{- end }}
    name: {{ .Values.webhook.certManager.issuerName }}
    {{- else }}
    name: {{ include "project-operator.fullname" . }}
    {{- end }}
  secretName: {{ include "project-operator.fullname" . }}-tls-managed
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-operator.fullname" . }}-tls
  labels:
    {{- include "project-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $data := (lookup "v1" "Secret" .Release.Namespace (printf "%s-tls" (include "project-operator.fullname" .))).data }}
  {{- if $data }}
  {{ $data | toYaml | nindent 2 }}
  {{- $caCert = index $data "ca.crt" }}
  {{- else }}
  {{- $cn := printf "%s.%s.svc" (include "project-operator.fullname" .) .Release.Namespace }}
  {{- $ca := genCA (printf "%s-ca" (include "project-operator.fullname" .)) 36500 }}
  {{- $cert := genSignedCert $cn nil (list $cn) 36500 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- $caCert = $ca.Cert | b64enc }}
  {{- end }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "project-operator.fullname" . }}
  labels:
    {{- include "project-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "project-operator.fullname" . }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if not .Values.webhook.certManager.enabled }}
    caBundle: {{ $caCert }}
    {{- end }}
    service:
      name: {{ include "project-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-core-cs-sap-com-v1alpha1-project
      port: 443
  name: validate.projects.core.cs.sap.com
  rules:
  - apiGroups:
    - core.cs.sap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - projects
    scope: Cluster
  matchPolicy: Equivalent
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Fail

